name: THE FLOAD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41301
title: THE FLOAD - R/EVOLUTIONIZING HIRING
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#354484'
    - '#ffffff'
    - '#9da4c3'
    - '#d5d8e5'
    - '#536096'
  brandStrength: 0.75
  lightness: 0.8111337046138942
  saturation: 0.7424525301903486
  rhythmicContrast: 0.9583512202370912
purpose: []
